#!/bin/bash
set -e

# KineticOps Agent install script (improved sampling)
# Usage:
# 1) Replace TOKEN placeholder below with the agent token you receive when you create/register an agent
#    e.g. TOKEN="<your-agent-token>"
# 2) Ensure SERVER_URL points to your backend (use http://<server>:8080 or https://...) if backend not on localhost
# 3) Run as root or with sudo

TOKEN="REPLACE_WITH_AGENT_TOKEN"
SERVER_URL="http://localhost:8080"

echo "Installing KineticOps Agent..."

# Create agent directory
sudo mkdir -p /opt/kineticops-agent
cd /opt/kineticops-agent

# Create agent script
sudo tee agent > /dev/null << 'EOF'
#!/bin/bash
# KineticOps Agent (install script generated by backend)
TOKEN="REPLACE_WITH_AGENT_TOKEN"
SERVER_URL="http://localhost:8080"

while true; do
    # CPU usage: compute fraction (0..1) from /proc/stat (two samples, 1s apart)
    CPU_USAGE=$(bash -lc 'read cpu user1 nice1 system1 idle1 rest < /proc/stat; sleep 1; read cpu user2 nice2 system2 idle2 rest < /proc/stat; prev_total=$((user1+nice1+system1+idle1)); total=$((user2+nice2+system2+idle2)); idle_diff=$((idle2-idle1)); total_diff=$((total-prev_total)); if [ "$total_diff" -gt 0 ]; then awk -v td="$total_diff" -v id="$idle_diff" "BEGIN { printf "%.4f", (td-id)/td }"; else echo "0"; fi' 2>/dev/null || echo "0")

    # Memory usage percent using /proc/meminfo
    MEMORY_USAGE=$(awk '/MemTotal/ {total=$2} /MemAvailable/ {avail=$2} END { if(total>0) printf "%.1f", (total-avail)/total*100; else print "0" }' /proc/meminfo 2>/dev/null || echo "0")

    # Disk usage percent for root mount
    DISK_USAGE=$(df --output=pcent / | tail -1 | tr -dc '0-9.' 2>/dev/null || echo "0")

    # Running services (top 10)
    SERVICES=$(systemctl list-units --type=service --state=running --no-pager --no-legend | head -10 | awk '{print $1}' | sed 's/.service$//' | tr '\n' ',' | sed 's/,$//' 2>/dev/null || echo "")

    # Send heartbeat (use JSON body, token identifies the agent)
    curl -s -X POST "${SERVER_URL}/api/v1/agents/heartbeat" \
        -H "Content-Type: application/json" \
        -d "{\"token\":\"${TOKEN}\",\"cpu_usage\":${CPU_USAGE:-0},\"memory_usage\":${MEMORY_USAGE:-0},\"disk_usage\":${DISK_USAGE:-0},\"services\":[],\"metadata\":{\"hostname\":\"$(hostname)\",\"os\":\"$(uname -s)\",\"kernel\":\"$(uname -r)\",\"uptime\":\"$(awk '{print int($1)}' /proc/uptime)\"}}" 2>/dev/null || echo "Heartbeat failed"

    sleep 30
done
EOF

sudo chmod +x agent

# Create systemd service
sudo tee /etc/systemd/system/kineticops-agent.service > /dev/null << EOF
[Unit]
Description=KineticOps Monitoring Agent
After=network.target

[Service]
Type=simple
User=root
WorkingDirectory=/opt/kineticops-agent
ExecStart=/opt/kineticops-agent/agent
Restart=always
RestartSec=10
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF

# Enable and start service
sudo systemctl daemon-reload
sudo systemctl enable kineticops-agent
sudo systemctl start kineticops-agent

echo "KineticOps Agent installed and started successfully!"
echo "Service status:"
sudo systemctl status kineticops-agent --no-pager -l
